/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................myCar.myDrive
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "myCar_myDrive_Automatic.h"
#include "ESDL_Linear_Interpolation.h"
/******************************************************************************
 * BEGIN: source code of a multiple instance class
 ******************************************************************************/





/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'myCar_myDrive_Automatic_move'
 * ----------------------------------------------------------------------------
 * model name:...................................'move'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void myCar_myDrive_Automatic_move (
               const struct myCar_myDrive_Automatic * self,
   /* IN    */ const float32                          powerCtrl,
   /* IN    */ const float32                          brakeCtrl,
   /* IN    */ const float32                          mydt,
   /* IN    */ const float32                          myg,
   /* IN    */ const float32                          recupCtrl
   )
{
   self->myCar_myDrive_Automatic_RAM->v
      = ((ESDL_Linear_CharTable1_getAt_r32r32(((&(self->myCar_myDrive_Automatic_CAL_MEM->BrakeMomentum)))->xSize, ((&(self->myCar_myDrive_Automatic_CAL_MEM->BrakeMomentum)))->xDist, ((&(self->myCar_myDrive_Automatic_CAL_MEM->BrakeMomentum)))->values, brakeCtrl) + self->myCar_myDrive_Automatic_RAM->momentum + ESDL_Linear_CharTable1_getAt_r32r32(((&(self->myCar_myDrive_Automatic_CAL_MEM->AirFriction)))->xSize, ((&(self->myCar_myDrive_Automatic_CAL_MEM->AirFriction)))->xDist, ((&(self->myCar_myDrive_Automatic_CAL_MEM->AirFriction)))->values, self->myCar_myDrive_Automatic_RAM->v) + self->myCar_myDrive_Automatic_RAM->recup_momentum + (myg * (((self->myCar_myDrive_Automatic_RAM->ds == 0.0F) ? self->myCar_myDrive_Automatic_RAM->dh : (self->myCar_myDrive_Automatic_RAM->dh / self->myCar_myDrive_Automatic_RAM->ds))) * 9.81F)) * mydt * 3.6F) + self->myCar_myDrive_Automatic_RAM->v;
   if (self->myCar_myDrive_Automatic_RAM->v < 0.0F)
   {
      self->myCar_myDrive_Automatic_RAM->v = 0.0F;
   } /* end if */
   self->myCar_myDrive_Automatic_RAM->ds
      = self->myCar_myDrive_Automatic_RAM->v * mydt * 2.77777777777778e-1F;
   if (self->myCar_myDrive_Automatic_RAM->ds > 0.001F)
   {
      self->myCar_myDrive_Automatic_RAM->dist
         = self->myCar_myDrive_Automatic_RAM->ds + self->myCar_myDrive_Automatic_RAM->dist;
   }
   else
   {
      self->myCar_myDrive_Automatic_RAM->ds = 0.001F;
   } /* end if */
   if (self->myCar_myDrive_Automatic_RAM->dist > self->myCar_myDrive_Automatic_CAL_MEM->TrackSize)
   {
      self->myCar_myDrive_Automatic_RAM->dist = 0.0F;
   } /* end if */
   self->myCar_myDrive_Automatic_RAM->dh
      = self->myCar_myDrive_Automatic_RAM->h - ESDL_Linear_CharTable1_getAt_r32r32(((&(self->myCar_myDrive_Automatic_CAL_MEM->Landscape)))->xSize, ((&(self->myCar_myDrive_Automatic_CAL_MEM->Landscape)))->xDist, ((&(self->myCar_myDrive_Automatic_CAL_MEM->Landscape)))->values, self->myCar_myDrive_Automatic_RAM->dist);
   self->myCar_myDrive_Automatic_RAM->h
      = ESDL_Linear_CharTable1_getAt_r32r32(((&(self->myCar_myDrive_Automatic_CAL_MEM->Landscape)))->xSize, ((&(self->myCar_myDrive_Automatic_CAL_MEM->Landscape)))->xDist, ((&(self->myCar_myDrive_Automatic_CAL_MEM->Landscape)))->values, self->myCar_myDrive_Automatic_RAM->dist);
   self->myCar_myDrive_Automatic_RAM->momentum
      = ESDL_Linear_CharTable2_getAt_r32r32r32(((&(self->myCar_myDrive_Automatic_CAL_MEM->EngineMomentum)))->xSize, ((&(self->myCar_myDrive_Automatic_CAL_MEM->EngineMomentum)))->xDist, ((&(self->myCar_myDrive_Automatic_CAL_MEM->EngineMomentum)))->ySize, ((&(self->myCar_myDrive_Automatic_CAL_MEM->EngineMomentum)))->yDist, ((&(self->myCar_myDrive_Automatic_CAL_MEM->EngineMomentum)))->values, self->myCar_myDrive_Automatic_RAM->power, self->myCar_myDrive_Automatic_RAM->v);
   self->myCar_myDrive_Automatic_RAM->recup_momentum
      = ESDL_Linear_CharTable1_getAt_r32r32(((&(self->myCar_myDrive_Automatic_CAL_MEM->curve_brake_recuperation_table)))->xSize, ((&(self->myCar_myDrive_Automatic_CAL_MEM->curve_brake_recuperation_table)))->xDist, ((&(self->myCar_myDrive_Automatic_CAL_MEM->curve_brake_recuperation_table)))->values, self->myCar_myDrive_Automatic_RAM->v) * recupCtrl * self->myCar_myDrive_Automatic_RAM->recupMult * 0.01F;
   self->myCar_myDrive_Automatic_RAM->battery
      = myCar_myBattery_myDrive_get_battery(&(self->myBattery_instance), self->myCar_myDrive_Automatic_RAM->momentum + self->myCar_myDrive_Automatic_RAM->recup_momentum, self->myCar_myDrive_Automatic_RAM->ds);
   self->BatteryState_instance.myCar_BatteryState_Automatic_RAM->battery = self->myCar_myDrive_Automatic_RAM->battery;
   self->BatteryState_instance.myCar_BatteryState_Automatic_RAM->powerInput = powerCtrl;
   myCar_BatteryState_Automatic_batteryStateStatemachineTrigger(&(self->BatteryState_instance));
   self->myCar_myDrive_Automatic_RAM->recupMult
      = self->BatteryState_instance.myCar_BatteryState_Automatic_RAM->recupMult;
   self->myCar_myDrive_Automatic_RAM->noRecupPossible
      = self->BatteryState_instance.myCar_BatteryState_Automatic_RAM->noRecupPossible;
   self->myCar_myDrive_Automatic_RAM->power
      = self->BatteryState_instance.myCar_BatteryState_Automatic_RAM->powerOverride;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'myCar_myDrive_Automatic_move'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



