/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................myCar.BatteryState
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "myCar_BatteryState_Automatic.h"
/******************************************************************************
 * BEGIN: source code of a multiple instance class
 ******************************************************************************/




/*-----------------------------------------------------------------------------
 *    Defines
 *----------------------------------------------------------------------------*/

#define BatteryEmpty 1U
#define BatteryFull 2U
#define BatteryNormal 0U
#define crawlModeState 3U



/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'myCar_BatteryState_Automatic_batteryStateStatemachineTrigger'
 * ----------------------------------------------------------------------------
 * model name:...................................'batteryStateStatemachineTrigger'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void myCar_BatteryState_Automatic_batteryStateStatemachineTrigger ( const struct myCar_BatteryState_Automatic * self)
{
   switch (self->myCar_BatteryState_Automatic_RAM->sm)
   {
      case BatteryEmpty:
         if (self->myCar_BatteryState_Automatic_RAM->battery > 0.0F)
         {
            self->myCar_BatteryState_Automatic_RAM->sm = crawlModeState;
            break;
         } /* end if */
         self->myCar_BatteryState_Automatic_RAM->powerOverride = 0.0F;
         break;
      case BatteryFull:
         if (self->myCar_BatteryState_Automatic_RAM->battery < 1.0F)
         {
            self->myCar_BatteryState_Automatic_RAM->sm = BatteryNormal;
            break;
         } /* end if */
         self->myCar_BatteryState_Automatic_RAM->noRecupPossible = true;
         self->myCar_BatteryState_Automatic_RAM->recupMult = 0.0F;
         self->myCar_BatteryState_Automatic_RAM->powerOverride = self->myCar_BatteryState_Automatic_RAM->powerInput;
         break;
      case crawlModeState:
         if (self->myCar_BatteryState_Automatic_RAM->battery == 0.0F)
         {
            self->myCar_BatteryState_Automatic_RAM->sm = BatteryEmpty;
            break;
         } /* end if */
         if (self->myCar_BatteryState_Automatic_RAM->battery > 0.0011F)
         {
            self->myCar_BatteryState_Automatic_RAM->sm = BatteryNormal;
            break;
         } /* end if */
         self->myCar_BatteryState_Automatic_RAM->powerOverride = self->myCar_BatteryState_Automatic_RAM->powerInput * 0.055F;
         break;
      case BatteryNormal:
      default:
         if (self->myCar_BatteryState_Automatic_RAM->battery >= 1.0F)
         {
            self->myCar_BatteryState_Automatic_RAM->sm = BatteryFull;
            break;
         } /* end if */
         if (self->myCar_BatteryState_Automatic_RAM->battery < 0.0011F)
         {
            self->myCar_BatteryState_Automatic_RAM->sm = crawlModeState;
            break;
         } /* end if */
         self->myCar_BatteryState_Automatic_RAM->noRecupPossible = false;
         self->myCar_BatteryState_Automatic_RAM->recupMult = 1.0F;
         self->myCar_BatteryState_Automatic_RAM->powerOverride = self->myCar_BatteryState_Automatic_RAM->powerInput;
         break;
   } /* end switch */
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'myCar_BatteryState_Automatic_batteryStateStatemachineTrigger'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'myCar_BatteryState_Automatic_esdl_getState'
 * ----------------------------------------------------------------------------
 * model name:...................................'esdl_getState'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

uint8 myCar_BatteryState_Automatic_esdl_getState ( const struct myCar_BatteryState_Automatic * self)
{
   return self->myCar_BatteryState_Automatic_RAM->sm;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'myCar_BatteryState_Automatic_esdl_getState'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



