/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................myCar.myBattery
 * REPRESENTATION:..............myDrive
 * DESCRIPTION:
 *    
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "myCar_myBattery_myDrive.h"
#include "myCar_myCar_Automatic.h"
/******************************************************************************
 * BEGIN: source code of a multiple instance class
 ******************************************************************************/





/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'myCar_myBattery_myDrive_get_battery'
 * ----------------------------------------------------------------------------
 * model name:...................................'get_battery'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 myCar_myBattery_myDrive_get_battery (
               const struct myCar_myBattery_myDrive * self,
   /* IN    */ const float32                          momentum,
   /* IN    */ const float32                          ds
   )
{
   /* temp. variables */
   float32 _t1real32;

   self->myCar_myBattery_myDrive_RAM->force = myCar_myCar_mass * momentum;
   self->myCar_myBattery_myDrive_RAM->energy = self->myCar_myBattery_myDrive_RAM->force * ds;
   self->myCar_myBattery_myDrive_RAM->e_kwh
      = self->myCar_myBattery_myDrive_RAM->energy * 2.77777777777778e-7F;
   _t1real32
      = self->myCar_myBattery_myDrive_RAM->battery - self->myCar_myBattery_myDrive_RAM->e_kwh;
   self->myCar_myBattery_myDrive_RAM->battery
      = ((_t1real32 >= 0.0F) ? (((_t1real32 <= 1.0F) ? _t1real32 : 1.0F)) : 0.0F);
   return self->myCar_myBattery_myDrive_RAM->battery;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'myCar_myBattery_myDrive_get_battery'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



