/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................myCar.myDriveUnitTest
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "myCar_myDriveUnitTest_Automatic.h"
#include "assertLib_Assert_Impl.h"
#include "MyCCF_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'myCar_myDriveUnitTest_CAL_MEM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * model name:...................................'myCar_myDriveUnitTest'
 * data set:.....................................'MYCAR_MYDRIVEUNITTEST_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct myCar_myDriveUnitTest_Automatic_CAL_MEM_SUBSTRUCT myCar_myDriveUnitTest_CAL_MEM = {
   /* struct element:'myCar_myDriveUnitTest_CAL_MEM.move_mydt' (modeled as:'move_mydt.myCar_myDriveUnitTest') */
   0.01F,
   /* struct element:'myCar_myDriveUnitTest_CAL_MEM.move_myg' (modeled as:'move_myg.myCar_myDriveUnitTest') */
   0.0F,
   /* substruct: myCar_myDriveUnitTest_CAL_MEM.tester (modeled as:'tester.myCar_myDriveUnitTest') */
   {
      /* struct element:'myCar_myDriveUnitTest_CAL_MEM.tester.TrackSize' (modeled as:'TrackSize.tester.myCar_myDriveUnitTest') */
      4413.58F,
      /* struct element:'myCar_myDriveUnitTest_CAL_MEM.tester.mass' (modeled as:'mass.tester.myCar_myDriveUnitTest') */
      1500.0F,
      /* substruct: myCar_myDriveUnitTest_CAL_MEM.tester.myBattery_instance (modeled as:'myBattery_instance.tester.myCar_myDriveUnitTest') */
      {
         /* struct element:'myCar_myDriveUnitTest_CAL_MEM.tester.myBattery_instance.mass' (modeled as:'mass.myBattery_instance.tester.myCar_myDriveUnitTest') */
         1500.0F
      },
      /* struct element:'myCar_myDriveUnitTest_CAL_MEM.tester.AirFriction' (modeled as:'AirFriction.tester.myCar_myDriveUnitTest') */
      {
         6U,
         {
            0.0F, 30.0F, 60.0F, 90.0F, 120.0F, 150.0F
         },
         {
            0.0F, -0.1F, -0.2F, -0.4F, -0.8F, -1.6F
         }
      },
      /* struct element:'myCar_myDriveUnitTest_CAL_MEM.tester.BrakeMomentum' (modeled as:'BrakeMomentum.tester.myCar_myDriveUnitTest') */
      {
         6U,
         {
            0.0F, 1.0F, 40.0F, 60.0F, 80.0F, 100.0F
         },
         {
            0.0F, 0.0F, -1.0F, -2.0F, -3.0F, -4.0F
         }
      },
      /* struct element:'myCar_myDriveUnitTest_CAL_MEM.tester.EngineMomentum' (modeled as:'EngineMomentum.tester.myCar_myDriveUnitTest') */
      {
         6U,
         6U,
         {
            0.0F, 5.0F, 20.0F, 60.126582278481F, 80.0F, 100.0F
         },
         {
            0.0F, 30.0F, 60.0F, 90.0F, 150.0F, 200.0F
         },
         {
            0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F,
            0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F,
            8.49999999999999e-1F, 0.6F, 0.3F, 0.0F, 0.0F, 0.0F,
            3.15F, 2.35F, 1.55F, 8.00000000000001e-1F, 3.99999999999999e-1F, 0.0F,
            4.5F, 3.6F, 2.7F, 1.5F, 0.9F, 0.0F,
            5.0F, 4.5F, 3.80000000000001F, 2.8F, 1.9F, 0.0F
         }
      },
      /* struct element:'myCar_myDriveUnitTest_CAL_MEM.tester.Landscape' (modeled as:'Landscape.tester.myCar_myDriveUnitTest') */
      {
         20U,
         {
            0.0F, 100.0F, 145.569620253165F, 202.53164556962F, 221.518987341772F, 240.0F,
            259.493670886076F, 300.0F, 350.0F, 400.0F, 450.0F, 500.0F, 600.0F, 700.0F,
            750.0F, 800.0F, 820.0F, 850.0F, 900.0F, 1000.0F
         },
         {
            0.0F, 0.0F, 4.0F, 7.125F, 10.375F, 10.75F, 10.5F, 9.0F, 5.375F, 2.625F, 0.625F,
            1.25F, 0.625F, 0.0F, 0.0F, 1.375F, 1.1F, 0.75F, 0.625F, 0.0F
         }
      },
      /* struct element:'myCar_myDriveUnitTest_CAL_MEM.tester.curve_brake_recuperation_table' (modeled as:'curve_brake_recuperation_table.tester.myCar_myDriveUnitTest') */
      {
         3U,
         {
            0.0F, 160.0F, 320.0F
         },
         {
            0.0F, -4.0F, -4.0F
         }
      }
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'myCar_myDriveUnitTest_CAL_MEM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'myCar_myDriveUnitTest_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'myCar_myDriveUnitTest'
 * data set:.....................................'MYCAR_MYDRIVEUNITTEST_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct myCar_myDriveUnitTest_Automatic_RAM_SUBSTRUCT myCar_myDriveUnitTest_RAM = {
   /* struct element:'myCar_myDriveUnitTest_RAM.move_brakeCtrl' (modeled as:'move_brakeCtrl.myCar_myDriveUnitTest') */
   0.0F,
   /* struct element:'myCar_myDriveUnitTest_RAM.move_powerCtrl' (modeled as:'move_powerCtrl.myCar_myDriveUnitTest') */
   20.0F,
   /* struct element:'myCar_myDriveUnitTest_RAM.move_recupCrtl' (modeled as:'move_recupCrtl.myCar_myDriveUnitTest') */
   0.0F,
   /* struct element:'myCar_myDriveUnitTest_RAM.time' (modeled as:'time.myCar_myDriveUnitTest') */
   0.0F,
   /* substruct: myCar_myDriveUnitTest_RAM.tester (modeled as:'tester.myCar_myDriveUnitTest') */
   {
      /* struct element:'myCar_myDriveUnitTest_RAM.tester.battery' (modeled as:'battery.tester.myCar_myDriveUnitTest') */
      0.0F,
      /* struct element:'myCar_myDriveUnitTest_RAM.tester.dh' (modeled as:'dh.tester.myCar_myDriveUnitTest') */
      0.0F,
      /* struct element:'myCar_myDriveUnitTest_RAM.tester.dist' (modeled as:'dist.tester.myCar_myDriveUnitTest') */
      0.0F,
      /* struct element:'myCar_myDriveUnitTest_RAM.tester.ds' (modeled as:'ds.tester.myCar_myDriveUnitTest') */
      0.0F,
      /* struct element:'myCar_myDriveUnitTest_RAM.tester.e_kwh' (modeled as:'e_kwh.tester.myCar_myDriveUnitTest') */
      0.0F,
      /* struct element:'myCar_myDriveUnitTest_RAM.tester.energy' (modeled as:'energy.tester.myCar_myDriveUnitTest') */
      0.0F,
      /* struct element:'myCar_myDriveUnitTest_RAM.tester.force' (modeled as:'force.tester.myCar_myDriveUnitTest') */
      0.0F,
      /* struct element:'myCar_myDriveUnitTest_RAM.tester.h' (modeled as:'h.tester.myCar_myDriveUnitTest') */
      0.0F,
      /* struct element:'myCar_myDriveUnitTest_RAM.tester.momentum' (modeled as:'momentum.tester.myCar_myDriveUnitTest') */
      0.0F,
      /* struct element:'myCar_myDriveUnitTest_RAM.tester.power' (modeled as:'power.tester.myCar_myDriveUnitTest') */
      0.0F,
      /* struct element:'myCar_myDriveUnitTest_RAM.tester.recupMult' (modeled as:'recupMult.tester.myCar_myDriveUnitTest') */
      0.0F,
      /* struct element:'myCar_myDriveUnitTest_RAM.tester.recup_momentum' (modeled as:'recup_momentum.tester.myCar_myDriveUnitTest') */
      0.0F,
      /* struct element:'myCar_myDriveUnitTest_RAM.tester.v' (modeled as:'v.tester.myCar_myDriveUnitTest') */
      0.0F,
      /* struct element:'myCar_myDriveUnitTest_RAM.tester.batteryOn' (modeled as:'batteryOn.tester.myCar_myDriveUnitTest') */
      false,
      /* struct element:'myCar_myDriveUnitTest_RAM.tester.noRecupPossible' (modeled as:'noRecupPossible.tester.myCar_myDriveUnitTest') */
      false,
      /* substruct: myCar_myDriveUnitTest_RAM.tester.BatteryState_instance (modeled as:'BatteryState_instance.tester.myCar_myDriveUnitTest') */
      {
         /* struct element:'myCar_myDriveUnitTest_RAM.tester.BatteryState_instance.battery' (modeled as:'battery.BatteryState_instance.tester.myCar_myDriveUnitTest') */
         0.0F,
         /* struct element:'myCar_myDriveUnitTest_RAM.tester.BatteryState_instance.powerInput' (modeled as:'powerInput.BatteryState_instance.tester.myCar_myDriveUnitTest') */
         0.0F,
         /* struct element:'myCar_myDriveUnitTest_RAM.tester.BatteryState_instance.powerOverride' (modeled as:'powerOverride.BatteryState_instance.tester.myCar_myDriveUnitTest') */
         0.0F,
         /* struct element:'myCar_myDriveUnitTest_RAM.tester.BatteryState_instance.recupMult' (modeled as:'recupMult.BatteryState_instance.tester.myCar_myDriveUnitTest') */
         0.0F,
         /* struct element:'myCar_myDriveUnitTest_RAM.tester.BatteryState_instance.noRecupPossible' (modeled as:'noRecupPossible.BatteryState_instance.tester.myCar_myDriveUnitTest') */
         false,
         /* struct element:'myCar_myDriveUnitTest_RAM.tester.BatteryState_instance.sm' (modeled as:'sm.BatteryState_instance.tester.myCar_myDriveUnitTest') */
         0U
      },
      /* substruct: myCar_myDriveUnitTest_RAM.tester.myBattery_instance (modeled as:'myBattery_instance.tester.myCar_myDriveUnitTest') */
      {
         /* struct element:'myCar_myDriveUnitTest_RAM.tester.myBattery_instance.battery' (modeled as:'battery.myBattery_instance.tester.myCar_myDriveUnitTest') */
         1.0F,
         /* struct element:'myCar_myDriveUnitTest_RAM.tester.myBattery_instance.e_kwh' (modeled as:'e_kwh.myBattery_instance.tester.myCar_myDriveUnitTest') */
         0.0F,
         /* struct element:'myCar_myDriveUnitTest_RAM.tester.myBattery_instance.energy' (modeled as:'energy.myBattery_instance.tester.myCar_myDriveUnitTest') */
         0.0F,
         /* struct element:'myCar_myDriveUnitTest_RAM.tester.myBattery_instance.force' (modeled as:'force.myBattery_instance.tester.myCar_myDriveUnitTest') */
         0.0F
      }
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'myCar_myDriveUnitTest_RAM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF COMPONENT VARIABLE 'myCar_myDriveUnitTest'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'myCar_myDriveUnitTest'
 * data set:.....................................'MYCAR_MYDRIVEUNITTEST_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const struct myCar_myDriveUnitTest_Automatic myCar_myDriveUnitTest = {
   /* substruct: myCar_myDriveUnitTest.tester (modeled as:'tester.myCar_myDriveUnitTest') */
   {
      /* type descriptor pointer 'myCar_myDrive_Automatic_CAL_MEM' for memory class substruct for 'CAL_MEM' */
      &myCar_myDriveUnitTest_CAL_MEM.tester,
      /* type descriptor pointer 'myCar_myDrive_Automatic_RAM' for memory class substruct for 'RAM' */
      &myCar_myDriveUnitTest_RAM.tester,
      /* substruct: myCar_myDriveUnitTest.tester.BatteryState_instance (modeled as:'BatteryState_instance.tester.myCar_myDriveUnitTest') */
      {
         /* type descriptor pointer 'myCar_BatteryState_Automatic_RAM' for memory class substruct for 'RAM' */
         &myCar_myDriveUnitTest_RAM.tester.BatteryState_instance
      },
      /* substruct: myCar_myDriveUnitTest.tester.myBattery_instance (modeled as:'myBattery_instance.tester.myCar_myDriveUnitTest') */
      {
         /* type descriptor pointer 'myCar_myBattery_myDrive_CAL_MEM' for memory class substruct for 'CAL_MEM' */
         &myCar_myDriveUnitTest_CAL_MEM.tester.myBattery_instance,
         /* type descriptor pointer 'myCar_myBattery_myDrive_RAM' for memory class substruct for 'RAM' */
         &myCar_myDriveUnitTest_RAM.tester.myBattery_instance
      }
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF COMPONENT VARIABLE 'myCar_myDriveUnitTest'
 ******************************************************************************/







/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'myCar_myDriveUnitTest_Automatic_move'
 * ----------------------------------------------------------------------------
 * model name:...................................'move'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void myCar_myDriveUnitTest_Automatic_move (void)
{
   while (myCar_myDriveUnitTest_RAM.tester.v < 20.0F)
   {
      myCar_myDrive_Automatic_move(&(myCar_myDriveUnitTest.tester), myCar_myDriveUnitTest_RAM.move_powerCtrl, myCar_myDriveUnitTest_RAM.move_brakeCtrl, myCar_myDriveUnitTest_CAL_MEM.move_mydt, myCar_myDriveUnitTest_CAL_MEM.move_myg, myCar_myDriveUnitTest_RAM.move_recupCrtl);
      myCar_Logging_Automatic_log(myCar_myDriveUnitTest_RAM.time, myCar_myDriveUnitTest_RAM.tester.v);
      myCar_myDriveUnitTest_RAM.time
         = myCar_myDriveUnitTest_RAM.time + myCar_myDriveUnitTest_CAL_MEM.move_mydt;
   } /* end while */
   ASSERT_NEAR((float64)myCar_myDriveUnitTest_RAM.tester.v, 20.0, 1.0);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'myCar_myDriveUnitTest_Automatic_move'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



