/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................myCar.myDriveTest
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "myCar_myDriveTest_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'myCar_myDriveTest_CAL_MEM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * model name:...................................'myCar_myDriveTest'
 * data set:.....................................'MYCAR_MYDRIVETEST_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct myCar_myDriveTest_Automatic_CAL_MEM_SUBSTRUCT myCar_myDriveTest_CAL_MEM = {
   /* struct element:'myCar_myDriveTest_CAL_MEM.move_brakeCtrl' (modeled as:'move_brakeCtrl.myCar_myDriveTest') */
   0.0F,
   /* struct element:'myCar_myDriveTest_CAL_MEM.move_mydt' (modeled as:'move_mydt.myCar_myDriveTest') */
   0.1F,
   /* struct element:'myCar_myDriveTest_CAL_MEM.move_myg' (modeled as:'move_myg.myCar_myDriveTest') */
   0.0F,
   /* struct element:'myCar_myDriveTest_CAL_MEM.move_powerCtrl' (modeled as:'move_powerCtrl.myCar_myDriveTest') */
   0.0F,
   /* struct element:'myCar_myDriveTest_CAL_MEM.move_recupCtrl' (modeled as:'move_recupCtrl.myCar_myDriveTest') */
   0.0F,
   /* substruct: myCar_myDriveTest_CAL_MEM.tester (modeled as:'tester.myCar_myDriveTest') */
   {
      /* struct element:'myCar_myDriveTest_CAL_MEM.tester.TrackSize' (modeled as:'TrackSize.tester.myCar_myDriveTest') */
      4413.58F,
      /* struct element:'myCar_myDriveTest_CAL_MEM.tester.mass' (modeled as:'mass.tester.myCar_myDriveTest') */
      1500.0F,
      /* substruct: myCar_myDriveTest_CAL_MEM.tester.myBattery_instance (modeled as:'myBattery_instance.tester.myCar_myDriveTest') */
      {
         /* struct element:'myCar_myDriveTest_CAL_MEM.tester.myBattery_instance.mass' (modeled as:'mass.myBattery_instance.tester.myCar_myDriveTest') */
         1500.0F
      },
      /* struct element:'myCar_myDriveTest_CAL_MEM.tester.AirFriction' (modeled as:'AirFriction.tester.myCar_myDriveTest') */
      {
         6U,
         {
            0.0F, 30.0F, 60.0F, 90.0F, 120.0F, 150.0F
         },
         {
            0.0F, -0.1F, -0.2F, -0.4F, -0.8F, -1.6F
         }
      },
      /* struct element:'myCar_myDriveTest_CAL_MEM.tester.BrakeMomentum' (modeled as:'BrakeMomentum.tester.myCar_myDriveTest') */
      {
         6U,
         {
            0.0F, 1.0F, 40.0F, 60.0F, 80.0F, 100.0F
         },
         {
            0.0F, 0.0F, -1.0F, -2.0F, -3.0F, -4.0F
         }
      },
      /* struct element:'myCar_myDriveTest_CAL_MEM.tester.EngineMomentum' (modeled as:'EngineMomentum.tester.myCar_myDriveTest') */
      {
         6U,
         6U,
         {
            0.0F, 5.0F, 20.0F, 60.126582278481F, 80.0F, 100.0F
         },
         {
            0.0F, 30.0F, 60.0F, 90.0F, 150.0F, 200.0F
         },
         {
            0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F,
            0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F,
            8.49999999999999e-1F, 0.6F, 0.3F, 0.0F, 0.0F, 0.0F,
            3.15F, 2.35F, 1.55F, 8.00000000000001e-1F, 3.99999999999999e-1F, 0.0F,
            4.5F, 3.6F, 2.7F, 1.5F, 0.9F, 0.0F,
            5.0F, 4.5F, 3.80000000000001F, 2.8F, 1.9F, 0.0F
         }
      },
      /* struct element:'myCar_myDriveTest_CAL_MEM.tester.Landscape' (modeled as:'Landscape.tester.myCar_myDriveTest') */
      {
         20U,
         {
            0.0F, 100.0F, 145.569620253165F, 202.53164556962F, 221.518987341772F, 240.0F,
            259.493670886076F, 300.0F, 350.0F, 400.0F, 450.0F, 500.0F, 600.0F, 700.0F,
            750.0F, 800.0F, 820.0F, 850.0F, 900.0F, 1000.0F
         },
         {
            0.0F, 0.0F, 4.0F, 7.125F, 10.375F, 10.75F, 10.5F, 9.0F, 5.375F, 2.625F, 0.625F,
            1.25F, 0.625F, 0.0F, 0.0F, 1.375F, 1.1F, 0.75F, 0.625F, 0.0F
         }
      },
      /* struct element:'myCar_myDriveTest_CAL_MEM.tester.curve_brake_recuperation_table' (modeled as:'curve_brake_recuperation_table.tester.myCar_myDriveTest') */
      {
         3U,
         {
            0.0F, 160.0F, 320.0F
         },
         {
            0.0F, -4.0F, -4.0F
         }
      }
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'myCar_myDriveTest_CAL_MEM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'myCar_myDriveTest_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'myCar_myDriveTest'
 * data set:.....................................'MYCAR_MYDRIVETEST_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct myCar_myDriveTest_Automatic_RAM_SUBSTRUCT myCar_myDriveTest_RAM = {
   /* substruct: myCar_myDriveTest_RAM.tester (modeled as:'tester.myCar_myDriveTest') */
   {
      /* struct element:'myCar_myDriveTest_RAM.tester.battery' (modeled as:'battery.tester.myCar_myDriveTest') */
      0.0F,
      /* struct element:'myCar_myDriveTest_RAM.tester.dh' (modeled as:'dh.tester.myCar_myDriveTest') */
      0.0F,
      /* struct element:'myCar_myDriveTest_RAM.tester.dist' (modeled as:'dist.tester.myCar_myDriveTest') */
      0.0F,
      /* struct element:'myCar_myDriveTest_RAM.tester.ds' (modeled as:'ds.tester.myCar_myDriveTest') */
      0.0F,
      /* struct element:'myCar_myDriveTest_RAM.tester.e_kwh' (modeled as:'e_kwh.tester.myCar_myDriveTest') */
      0.0F,
      /* struct element:'myCar_myDriveTest_RAM.tester.energy' (modeled as:'energy.tester.myCar_myDriveTest') */
      0.0F,
      /* struct element:'myCar_myDriveTest_RAM.tester.force' (modeled as:'force.tester.myCar_myDriveTest') */
      0.0F,
      /* struct element:'myCar_myDriveTest_RAM.tester.h' (modeled as:'h.tester.myCar_myDriveTest') */
      0.0F,
      /* struct element:'myCar_myDriveTest_RAM.tester.momentum' (modeled as:'momentum.tester.myCar_myDriveTest') */
      0.0F,
      /* struct element:'myCar_myDriveTest_RAM.tester.power' (modeled as:'power.tester.myCar_myDriveTest') */
      0.0F,
      /* struct element:'myCar_myDriveTest_RAM.tester.recupMult' (modeled as:'recupMult.tester.myCar_myDriveTest') */
      0.0F,
      /* struct element:'myCar_myDriveTest_RAM.tester.recup_momentum' (modeled as:'recup_momentum.tester.myCar_myDriveTest') */
      0.0F,
      /* struct element:'myCar_myDriveTest_RAM.tester.v' (modeled as:'v.tester.myCar_myDriveTest') */
      0.0F,
      /* struct element:'myCar_myDriveTest_RAM.tester.batteryOn' (modeled as:'batteryOn.tester.myCar_myDriveTest') */
      false,
      /* struct element:'myCar_myDriveTest_RAM.tester.noRecupPossible' (modeled as:'noRecupPossible.tester.myCar_myDriveTest') */
      false,
      /* substruct: myCar_myDriveTest_RAM.tester.BatteryState_instance (modeled as:'BatteryState_instance.tester.myCar_myDriveTest') */
      {
         /* struct element:'myCar_myDriveTest_RAM.tester.BatteryState_instance.battery' (modeled as:'battery.BatteryState_instance.tester.myCar_myDriveTest') */
         0.0F,
         /* struct element:'myCar_myDriveTest_RAM.tester.BatteryState_instance.powerInput' (modeled as:'powerInput.BatteryState_instance.tester.myCar_myDriveTest') */
         0.0F,
         /* struct element:'myCar_myDriveTest_RAM.tester.BatteryState_instance.powerOverride' (modeled as:'powerOverride.BatteryState_instance.tester.myCar_myDriveTest') */
         0.0F,
         /* struct element:'myCar_myDriveTest_RAM.tester.BatteryState_instance.recupMult' (modeled as:'recupMult.BatteryState_instance.tester.myCar_myDriveTest') */
         0.0F,
         /* struct element:'myCar_myDriveTest_RAM.tester.BatteryState_instance.noRecupPossible' (modeled as:'noRecupPossible.BatteryState_instance.tester.myCar_myDriveTest') */
         false,
         /* struct element:'myCar_myDriveTest_RAM.tester.BatteryState_instance.sm' (modeled as:'sm.BatteryState_instance.tester.myCar_myDriveTest') */
         0U
      },
      /* substruct: myCar_myDriveTest_RAM.tester.myBattery_instance (modeled as:'myBattery_instance.tester.myCar_myDriveTest') */
      {
         /* struct element:'myCar_myDriveTest_RAM.tester.myBattery_instance.battery' (modeled as:'battery.myBattery_instance.tester.myCar_myDriveTest') */
         1.0F,
         /* struct element:'myCar_myDriveTest_RAM.tester.myBattery_instance.e_kwh' (modeled as:'e_kwh.myBattery_instance.tester.myCar_myDriveTest') */
         0.0F,
         /* struct element:'myCar_myDriveTest_RAM.tester.myBattery_instance.energy' (modeled as:'energy.myBattery_instance.tester.myCar_myDriveTest') */
         0.0F,
         /* struct element:'myCar_myDriveTest_RAM.tester.myBattery_instance.force' (modeled as:'force.myBattery_instance.tester.myCar_myDriveTest') */
         0.0F
      }
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'myCar_myDriveTest_RAM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF COMPONENT VARIABLE 'myCar_myDriveTest'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'myCar_myDriveTest'
 * data set:.....................................'MYCAR_MYDRIVETEST_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const struct myCar_myDriveTest_Automatic myCar_myDriveTest = {
   /* substruct: myCar_myDriveTest.tester (modeled as:'tester.myCar_myDriveTest') */
   {
      /* type descriptor pointer 'myCar_myDrive_Automatic_CAL_MEM' for memory class substruct for 'CAL_MEM' */
      &myCar_myDriveTest_CAL_MEM.tester,
      /* type descriptor pointer 'myCar_myDrive_Automatic_RAM' for memory class substruct for 'RAM' */
      &myCar_myDriveTest_RAM.tester,
      /* substruct: myCar_myDriveTest.tester.BatteryState_instance (modeled as:'BatteryState_instance.tester.myCar_myDriveTest') */
      {
         /* type descriptor pointer 'myCar_BatteryState_Automatic_RAM' for memory class substruct for 'RAM' */
         &myCar_myDriveTest_RAM.tester.BatteryState_instance
      },
      /* substruct: myCar_myDriveTest.tester.myBattery_instance (modeled as:'myBattery_instance.tester.myCar_myDriveTest') */
      {
         /* type descriptor pointer 'myCar_myBattery_myDrive_CAL_MEM' for memory class substruct for 'CAL_MEM' */
         &myCar_myDriveTest_CAL_MEM.tester.myBattery_instance,
         /* type descriptor pointer 'myCar_myBattery_myDrive_RAM' for memory class substruct for 'RAM' */
         &myCar_myDriveTest_RAM.tester.myBattery_instance
      }
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF COMPONENT VARIABLE 'myCar_myDriveTest'
 ******************************************************************************/







/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF PROCESS 'myCar_myDriveTest_Automatic_move'
 * ----------------------------------------------------------------------------
 * model name:...................................'move'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void myCar_myDriveTest_Automatic_move (void)
{
   myCar_myDrive_Automatic_move(&(myCar_myDriveTest.tester), myCar_myDriveTest_CAL_MEM.move_powerCtrl, myCar_myDriveTest_CAL_MEM.move_brakeCtrl, myCar_myDriveTest_CAL_MEM.move_mydt, myCar_myDriveTest_CAL_MEM.move_myg, myCar_myDriveTest_CAL_MEM.move_recupCtrl);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF PROCESS 'myCar_myDriveTest_Automatic_move'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'myCar_myDriveTest_Automatic_testCrawlDistance'
 * ----------------------------------------------------------------------------
 * model name:...................................'testCrawlDistance'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void myCar_myDriveTest_Automatic_testCrawlDistance (void)
{
   /* user defined local variables */
   float32 currentBattery;
   float32 distCounter;
   float32 myBatteryLevels[5];

   myBatteryLevels[0U] = 0.3F;
   myBatteryLevels[1U] = 0.2F;
   myBatteryLevels[2U] = 0.1F;
   myBatteryLevels[3U] = 0.05F;
   myBatteryLevels[4U] = 0.03F;
   distCounter = 0.0F;
   currentBattery = 0.0F;
   myCar_myDrive_Automatic_move(&(myCar_myDriveTest.tester), 10.0F, myCar_myDriveTest_CAL_MEM.move_brakeCtrl, myCar_myDriveTest_CAL_MEM.move_mydt, myCar_myDriveTest_CAL_MEM.move_myg, myCar_myDriveTest_CAL_MEM.move_recupCtrl);
   myCar_myDrive_Automatic_move(&(myCar_myDriveTest.tester), 10.0F, myCar_myDriveTest_CAL_MEM.move_brakeCtrl, myCar_myDriveTest_CAL_MEM.move_mydt, myCar_myDriveTest_CAL_MEM.move_myg, myCar_myDriveTest_CAL_MEM.move_recupCtrl);
   while (myCar_myDriveTest_RAM.tester.v < 7.0F)
   {
      myCar_myDrive_Automatic_move(&(myCar_myDriveTest.tester), 6.0F, myCar_myDriveTest_CAL_MEM.move_brakeCtrl, myCar_myDriveTest_CAL_MEM.move_mydt, myCar_myDriveTest_CAL_MEM.move_myg, myCar_myDriveTest_CAL_MEM.move_recupCtrl);
   } /* end while */
   currentBattery = myCar_myDriveTest_RAM.tester.battery;
   distCounter = myCar_myDriveTest_RAM.tester.dist;
   while (myCar_myDriveTest_RAM.tester.dist < (distCounter + 100.0F))
   {
      myCar_myDrive_Automatic_move(&(myCar_myDriveTest.tester), 5.5F, myCar_myDriveTest_CAL_MEM.move_brakeCtrl, myCar_myDriveTest_CAL_MEM.move_mydt, myCar_myDriveTest_CAL_MEM.move_myg, myCar_myDriveTest_CAL_MEM.move_recupCtrl);
   } /* end while */
   myCar_Logging_Automatic_log(currentBattery - myCar_myDriveTest_RAM.tester.battery, myCar_myDriveTest_RAM.tester.dist - distCounter);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'myCar_myDriveTest_Automatic_testCrawlDistance'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



