/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................myCar.BatteryState
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    Private access macros
 ******************************************************************************/
#ifndef ESDL_MYCAR_BATTERYSTATE_AUTOMATIC_PRIVATE
#define ESDL_MYCAR_BATTERYSTATE_AUTOMATIC_PRIVATE

/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define noRecupPossible_VAL self->myCar_BatteryState_Automatic_RAM->noRecupPossible
#define recupMult_VAL self->myCar_BatteryState_Automatic_RAM->recupMult
#define powerOverride_VAL self->myCar_BatteryState_Automatic_RAM->powerOverride
#define powerInput_VAL self->myCar_BatteryState_Automatic_RAM->powerInput
#define battery_VAL self->myCar_BatteryState_Automatic_RAM->battery
#define sm_VAL self->myCar_BatteryState_Automatic_RAM->sm
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* ESDL_MYCAR_BATTERYSTATE_AUTOMATIC_PRIVATE */

