/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................myCar.SplitSignal
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_MYCAR_SPLITSIGNAL_AUTOMATIC_H_
#define _ASD_MYCAR_SPLITSIGNAL_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#if (!defined(ESDL_HEADER_VERSION) || (ESDL_HEADER_VERSION < 5))
# error NOT COMPLIANT (< compliance level 5) VERSION OF esdl.h FOUND; To fix that, delete the old headers (esdl_<...>.h) in include folder and restart build again to get the new version of those files.
#endif
#include "chartab.h"
#include "SystemLib_Comparators_GreaterZero_Impl.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'myCar_SplitSignal_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct myCar_SplitSignal_Automatic_RAM_SUBSTRUCT {
   float32 minus;
   float32 plus;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'myCar_SplitSignal_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR CLASS 'myCar_SplitSignal_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct myCar_SplitSignal_Automatic {
   struct myCar_SplitSignal_Automatic_RAM_SUBSTRUCT * myCar_SplitSignal_Automatic_RAM;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR CLASS 'myCar_SplitSignal_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ................myCar_SplitSignal_Automatic */
#define _myCar_SplitSignal_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by class myCar_SplitSignal_Automatic
 ******************************************************************************/
extern void myCar_SplitSignal_Automatic_calc (
               const struct myCar_SplitSignal_Automatic * self,
   /* IN    */ const float32                              arg
   );



#endif /* _ASD_MYCAR_SPLITSIGNAL_AUTOMATIC_H_ */
