/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................myCar.myDrive
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    Private access macros
 ******************************************************************************/
#ifndef ESDL_MYCAR_MYDRIVE_AUTOMATIC_PRIVATE
#define ESDL_MYCAR_MYDRIVE_AUTOMATIC_PRIVATE

/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define BrakeMomentum_VAL self->myCar_myDrive_Automatic_CAL_MEM->BrakeMomentum
#define BrakeMomentum_REF &(self->myCar_myDrive_Automatic_CAL_MEM->BrakeMomentum)
#define EngineMomentum_VAL self->myCar_myDrive_Automatic_CAL_MEM->EngineMomentum
#define EngineMomentum_REF &(self->myCar_myDrive_Automatic_CAL_MEM->EngineMomentum)
#define AirFriction_VAL self->myCar_myDrive_Automatic_CAL_MEM->AirFriction
#define AirFriction_REF &(self->myCar_myDrive_Automatic_CAL_MEM->AirFriction)
#define ds_VAL self->myCar_myDrive_Automatic_RAM->ds
#define momentum_VAL self->myCar_myDrive_Automatic_RAM->momentum
#define dist_VAL self->myCar_myDrive_Automatic_RAM->dist
#define v_VAL self->myCar_myDrive_Automatic_RAM->v
#define battery_VAL self->myCar_myDrive_Automatic_RAM->battery
#define cbrt_VAL self->myCar_myDrive_Automatic_CAL_MEM->cbrt
#define cbrt_REF &(self->myCar_myDrive_Automatic_CAL_MEM->cbrt)
#define recup_momentum_VAL self->myCar_myDrive_Automatic_RAM->recup_momentum
#define noRecupPossible_VAL self->myCar_myDrive_Automatic_RAM->noRecupPossible
#define recupMult_VAL self->myCar_myDrive_Automatic_RAM->recupMult
#define power_VAL self->myCar_myDrive_Automatic_RAM->power
#define totalDist_VAL self->myCar_myDrive_Automatic_RAM->totalDist
#define DistanceManager_instance_VAL self->DistanceManager_instance
#define DistanceManager_instance_REF &(self->DistanceManager_instance)
#define BatteryManager_instance_VAL self->BatteryManager_instance
#define BatteryManager_instance_REF &(self->BatteryManager_instance)
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* ESDL_MYCAR_MYDRIVE_AUTOMATIC_PRIVATE */

