/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................myCar.myCar
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    Private access macros
 ******************************************************************************/
#ifndef ESDL_MYCAR_MYCAR_AUTOMATIC_PRIVATE
#define ESDL_MYCAR_MYCAR_AUTOMATIC_PRIVATE

/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define g_VAL myCar_myCar_CAL_MEM.g
#define myDrive_instance_VAL myCar_myCar.myDrive_instance
#define myDrive_instance_REF &(myCar_myCar.myDrive_instance)
#define myCar_myCar_mass_VAL myCar_myCar_mass
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* ESDL_MYCAR_MYCAR_AUTOMATIC_PRIVATE */

