/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................myCar.myDrive
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_MYCAR_MYDRIVE_AUTOMATIC_H_
#define _ASD_MYCAR_MYDRIVE_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#if (!defined(ESDL_HEADER_VERSION) || (ESDL_HEADER_VERSION < 5))
# error NOT COMPLIANT (< compliance level 5) VERSION OF esdl.h FOUND; To fix that, delete the old headers (esdl_<...>.h) in include folder and restart build again to get the new version of those files.
#endif
#include "chartab.h"
#include "myCar_BatteryManager_Automatic.h"
#include "myCar_DistanceManager_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'myCar_myDrive_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * ---------------------------------------------------------------------------*/
struct myCar_myDrive_Automatic_CAL_MEM_SUBSTRUCT {
   struct myCar_BatteryManager_Automatic_CAL_MEM_SUBSTRUCT BatteryManager_instance;
   struct myCar_DistanceManager_Automatic_CAL_MEM_SUBSTRUCT DistanceManager_instance;
   struct CharTable1_real32_6_real32_TYPE AirFriction;
   struct CharTable1_real32_6_real32_TYPE BrakeMomentum;
   struct CharTable2_real32_6_real32_6_real32_TYPE EngineMomentum;
   struct CharTable1_real32_3_real32_TYPE cbrt;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'myCar_myDrive_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'myCar_myDrive_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct myCar_myDrive_Automatic_RAM_SUBSTRUCT {
   float32 battery;
   float32 dist;
   float32 ds;
   float32 momentum;
   float32 power;
   float32 recupMult;
   float32 recup_momentum;
   float32 totalDist;
   float32 v;
   boolean noRecupPossible;
   struct myCar_BatteryManager_Automatic_RAM_SUBSTRUCT BatteryManager_instance;
   struct myCar_DistanceManager_Automatic_RAM_SUBSTRUCT DistanceManager_instance;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'myCar_myDrive_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR CLASS 'myCar_myDrive_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct myCar_myDrive_Automatic {
   struct myCar_myDrive_Automatic_CAL_MEM_SUBSTRUCT * myCar_myDrive_Automatic_CAL_MEM;
   struct myCar_myDrive_Automatic_RAM_SUBSTRUCT * myCar_myDrive_Automatic_RAM;
   struct myCar_BatteryManager_Automatic BatteryManager_instance;
   struct myCar_DistanceManager_Automatic DistanceManager_instance;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR CLASS 'myCar_myDrive_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ....................myCar_myDrive_Automatic */
#define _myCar_myDrive_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by class myCar_myDrive_Automatic
 ******************************************************************************/
extern void myCar_myDrive_Automatic_move (
               const struct myCar_myDrive_Automatic * self,
   /* IN    */ const float32                          powerCtrl,
   /* IN    */ const float32                          brakeCtrl,
   /* IN    */ const float32                          mydt,
   /* IN    */ const float32                          myg,
   /* IN    */ const float32                          recupCtrl
   );



#endif /* _ASD_MYCAR_MYDRIVE_AUTOMATIC_H_ */
