/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................myCar.TargetVelocity
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_MYCAR_TARGETVELOCITY_AUTOMATIC_H_
#define _ASD_MYCAR_TARGETVELOCITY_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#if (!defined(ESDL_HEADER_VERSION) || (ESDL_HEADER_VERSION < 5))
# error NOT COMPLIANT (< compliance level 5) VERSION OF esdl.h FOUND; To fix that, delete the old headers (esdl_<...>.h) in include folder and restart build again to get the new version of those files.
#endif
#include "chartab.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'myCar_TargetVelocity_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * ---------------------------------------------------------------------------*/
struct myCar_TargetVelocity_Automatic_CAL_MEM_SUBSTRUCT {
   float32 dv;
   float32 mn;
   float32 mx;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'myCar_TargetVelocity_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'myCar_TargetVelocity_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct myCar_TargetVelocity_Automatic_RAM_SUBSTRUCT {
   float32 v;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'myCar_TargetVelocity_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR CLASS 'myCar_TargetVelocity_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct myCar_TargetVelocity_Automatic {
   struct myCar_TargetVelocity_Automatic_CAL_MEM_SUBSTRUCT * myCar_TargetVelocity_Automatic_CAL_MEM;
   struct myCar_TargetVelocity_Automatic_RAM_SUBSTRUCT * myCar_TargetVelocity_Automatic_RAM;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR CLASS 'myCar_TargetVelocity_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: .............myCar_TargetVelocity_Automatic */
#define _myCar_TargetVelocity_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by class myCar_TargetVelocity_Automatic
 ******************************************************************************/
extern void myCar_TargetVelocity_Automatic_dec ( const struct myCar_TargetVelocity_Automatic * self);
extern void myCar_TargetVelocity_Automatic_inc ( const struct myCar_TargetVelocity_Automatic * self);
extern void myCar_TargetVelocity_Automatic_reset (
               const struct myCar_TargetVelocity_Automatic * self,
   /* IN    */ const float32                                 arg
   );
extern float32 myCar_TargetVelocity_Automatic_velocity ( const struct myCar_TargetVelocity_Automatic * self);



#endif /* _ASD_MYCAR_TARGETVELOCITY_AUTOMATIC_H_ */
