/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................myCar.CCFState
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_MYCAR_CCFSTATE_AUTOMATIC_H_
#define _ASD_MYCAR_CCFSTATE_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#if (!defined(ESDL_HEADER_VERSION) || (ESDL_HEADER_VERSION < 5))
# error NOT COMPLIANT (< compliance level 5) VERSION OF esdl.h FOUND; To fix that, delete the old headers (esdl_<...>.h) in include folder and restart build again to get the new version of those files.
#endif
#include "chartab.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'myCar_CCFState_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct myCar_CCFState_Automatic_RAM_SUBSTRUCT {
   float32 br;
   float32 bra;
   float32 ctrl;
   float32 pow;
   float32 pw;
   boolean act;
   boolean on;
   uint8 sm;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'myCar_CCFState_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR CLASS 'myCar_CCFState_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct myCar_CCFState_Automatic {
   struct myCar_CCFState_Automatic_RAM_SUBSTRUCT * myCar_CCFState_Automatic_RAM;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR CLASS 'myCar_CCFState_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ...................myCar_CCFState_Automatic */
#define _myCar_CCFState_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by class myCar_CCFState_Automatic
 ******************************************************************************/
extern void myCar_CCFState_Automatic_cCFStateStatemachineTrigger ( const struct myCar_CCFState_Automatic * self);
uint8 myCar_CCFState_Automatic_esdl_getState ( const struct myCar_CCFState_Automatic * self);



#endif /* _ASD_MYCAR_CCFSTATE_AUTOMATIC_H_ */
