/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................myCar.CCF
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    Private access macros
 ******************************************************************************/
#ifndef ESDL_MYCAR_CCF_AUTOMATIC_PRIVATE
#define ESDL_MYCAR_CCF_AUTOMATIC_PRIVATE

/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define vsoll_VAL myCar_CCF_RAM.vsoll
#define TVI_VAL myCar_CCF.TVI
#define TVI_REF &(myCar_CCF.TVI)
#define OnRising_VAL myCar_CCF.OnRising
#define OnRising_REF &(myCar_CCF.OnRising)
#define PID_instance_VAL myCar_CCF.PID_instance
#define PID_instance_REF &(myCar_CCF.PID_instance)
#define K_VAL myCar_CCF_CAL_MEM.K
#define TV_VAL myCar_CCF_CAL_MEM.TV
#define TN_VAL myCar_CCF_CAL_MEM.TN
#define IncRising_VAL myCar_CCF.IncRising
#define IncRising_REF &(myCar_CCF.IncRising)
#define DecRising_VAL myCar_CCF.DecRising
#define DecRising_REF &(myCar_CCF.DecRising)
#define GZ_VAL myCar_CCF.GZ
#define GZ_REF &(myCar_CCF.GZ)
#define SplitSignal_instance_VAL myCar_CCF.SplitSignal_instance
#define SplitSignal_instance_REF &(myCar_CCF.SplitSignal_instance)
#define CCFS_VAL myCar_CCF.CCFS
#define CCFS_REF &(myCar_CCF.CCFS)
#define Limiter_instance_VAL myCar_CCF.Limiter_instance
#define Limiter_instance_REF &(myCar_CCF.Limiter_instance)
#define mn_VAL myCar_CCF_CAL_MEM.mn
#define mx_VAL myCar_CCF_CAL_MEM.mx
#define vs_VAL myCar_CCF_CAL_MEM.vs
#define ctl_VAL myCar_CCF_RAM.ctl
#define brake_VAL myCar_CCF_CAL_MEM.brake
#define power_VAL myCar_CCF_CAL_MEM.power
#define withRecup_VAL myCar_CCF_CAL_MEM.withRecup
#define br_VAL myCar_CCF_RAM.br
#define c_VAL myCar_CCF_CAL_MEM.c
#define PI_instance_VAL myCar_CCF.PI_instance
#define PI_instance_REF &(myCar_CCF.PI_instance)
#define useSilly_VAL myCar_CCF_CAL_MEM.useSilly
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* ESDL_MYCAR_CCF_AUTOMATIC_PRIVATE */

