/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................myCar.Driver
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/


/*-----------------------------------------------------------------------------
 *    Defines
 *----------------------------------------------------------------------------*/

#define __ASD_REQUIRES_OS_INFACE

/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "myCar_Driver_Automatic.h"
#include "resources_CarMessages_Automatic.h"
#include "resources_DriverMessages_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'myCar_Driver_CAL_MEM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * model name:...................................'myCar_Driver'
 * data set:.....................................'MYCAR_DRIVER_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct myCar_Driver_Automatic_CAL_MEM_SUBSTRUCT myCar_Driver_CAL_MEM = {
   /* struct element:'myCar_Driver_CAL_MEM.brake' (modeled as:'brake.myCar_Driver') */
   0.0F,
   /* struct element:'myCar_Driver_CAL_MEM.manual_recup' (modeled as:'manual_recup.myCar_Driver') */
   0.0F,
   /* struct element:'myCar_Driver_CAL_MEM.power' (modeled as:'power.myCar_Driver') */
   0.0F,
   /* struct element:'myCar_Driver_CAL_MEM.dec' (modeled as:'dec.myCar_Driver') */
   false,
   /* struct element:'myCar_Driver_CAL_MEM.inc' (modeled as:'inc.myCar_Driver') */
   false,
   /* struct element:'myCar_Driver_CAL_MEM.on' (modeled as:'on.myCar_Driver') */
   false
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'myCar_Driver_CAL_MEM'
 ******************************************************************************/

/******************************************************************************
 * DEFINITION OF COMPONENT VARIABLE OMITTED
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'myCar_Driver'
 * reason:.......................................no local elements
 * ---------------------------------------------------------------------------*/





#define brake_VAL (myCar_Driver_CAL_MEM.brake)
#define dec_VAL (myCar_Driver_CAL_MEM.dec)
#define inc_VAL (myCar_Driver_CAL_MEM.inc)
#define manual_recup_VAL (myCar_Driver_CAL_MEM.manual_recup)
#define on_VAL (myCar_Driver_CAL_MEM.on)
#define power_VAL (myCar_Driver_CAL_MEM.power)


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF PROCESS 'myCar_Driver_Automatic_calc'
 * ----------------------------------------------------------------------------
 * model name:...................................'calc'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/
/* messages used by this process */


void myCar_Driver_Automatic_calc (void)
{
   /* define local message copies */
   float32 resources_CarMessages_recuperation__myCar_Driver_Automatic_calc;
   float32 resources_DriverMessages_brake__myCar_Driver_Automatic_calc;
   boolean resources_DriverMessages_decrement__myCar_Driver_Automatic_calc;
   boolean resources_DriverMessages_increment__myCar_Driver_Automatic_calc;
   boolean resources_DriverMessages_on__myCar_Driver_Automatic_calc;
   float32 resources_DriverMessages_power__myCar_Driver_Automatic_calc;
   /* receive messages implicitly */
   {
      DisableAllInterrupts();
      resources_CarMessages_recuperation__myCar_Driver_Automatic_calc = resources_CarMessages_recuperation;
      resources_DriverMessages_brake__myCar_Driver_Automatic_calc = resources_DriverMessages_brake;
      resources_DriverMessages_decrement__myCar_Driver_Automatic_calc = resources_DriverMessages_decrement;
      resources_DriverMessages_increment__myCar_Driver_Automatic_calc = resources_DriverMessages_increment;
      resources_DriverMessages_on__myCar_Driver_Automatic_calc = resources_DriverMessages_on;
      resources_DriverMessages_power__myCar_Driver_Automatic_calc = resources_DriverMessages_power;
      EnableAllInterrupts();
   }
   resources_DriverMessages_power__myCar_Driver_Automatic_calc = power_VAL;
   resources_DriverMessages_brake__myCar_Driver_Automatic_calc = brake_VAL;
   resources_DriverMessages_on__myCar_Driver_Automatic_calc = on_VAL;
   resources_DriverMessages_increment__myCar_Driver_Automatic_calc = inc_VAL;
   resources_DriverMessages_decrement__myCar_Driver_Automatic_calc = dec_VAL;
   resources_CarMessages_recuperation__myCar_Driver_Automatic_calc = manual_recup_VAL;
   /* send messages implicitly */
   {
      DisableAllInterrupts();
      resources_CarMessages_recuperation = resources_CarMessages_recuperation__myCar_Driver_Automatic_calc;
      resources_DriverMessages_brake = resources_DriverMessages_brake__myCar_Driver_Automatic_calc;
      resources_DriverMessages_decrement = resources_DriverMessages_decrement__myCar_Driver_Automatic_calc;
      resources_DriverMessages_increment = resources_DriverMessages_increment__myCar_Driver_Automatic_calc;
      resources_DriverMessages_on = resources_DriverMessages_on__myCar_Driver_Automatic_calc;
      resources_DriverMessages_power = resources_DriverMessages_power__myCar_Driver_Automatic_calc;
      EnableAllInterrupts();
   }
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF PROCESS 'myCar_Driver_Automatic_calc'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



