/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................myCar.SplitSignal
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    Private access macros
 ******************************************************************************/
#ifndef ESDL_MYCAR_SPLITSIGNAL_AUTOMATIC_PRIVATE
#define ESDL_MYCAR_SPLITSIGNAL_AUTOMATIC_PRIVATE

/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define plus_VAL self->myCar_SplitSignal_Automatic_RAM->plus
#define minus_VAL self->myCar_SplitSignal_Automatic_RAM->minus
#define GZ_VAL self->GZ
#define GZ_REF &(self->GZ)
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* ESDL_MYCAR_SPLITSIGNAL_AUTOMATIC_PRIVATE */

