/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................myCar.CCFState
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    Private access macros
 ******************************************************************************/
#ifndef ESDL_MYCAR_CCFSTATE_AUTOMATIC_PRIVATE
#define ESDL_MYCAR_CCFSTATE_AUTOMATIC_PRIVATE

/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define pow_VAL self->myCar_CCFState_Automatic_RAM->pow
#define bra_VAL self->myCar_CCFState_Automatic_RAM->bra
#define pw_VAL self->myCar_CCFState_Automatic_RAM->pw
#define br_VAL self->myCar_CCFState_Automatic_RAM->br
#define on_VAL self->myCar_CCFState_Automatic_RAM->on
#define act_VAL self->myCar_CCFState_Automatic_RAM->act
#define ctrl_VAL self->myCar_CCFState_Automatic_RAM->ctrl
#define sm_VAL self->myCar_CCFState_Automatic_RAM->sm
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* ESDL_MYCAR_CCFSTATE_AUTOMATIC_PRIVATE */

