/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................myCar.myBattery
 * REPRESENTATION:..............myDrive
 * DESCRIPTION:
 *    Private access macros
 ******************************************************************************/
#ifndef ESDL_MYCAR_MYBATTERY_MYDRIVE_PRIVATE
#define ESDL_MYCAR_MYBATTERY_MYDRIVE_PRIVATE

/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define force_VAL self->myCar_myBattery_myDrive_RAM->force
#define mass_VAL self->myCar_myBattery_myDrive_CAL_MEM->mass
#define energy_VAL self->myCar_myBattery_myDrive_RAM->energy
#define e_kwh_VAL self->myCar_myBattery_myDrive_RAM->e_kwh
#define battery_VAL self->myCar_myBattery_myDrive_RAM->battery
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* ESDL_MYCAR_MYBATTERY_MYDRIVE_PRIVATE */

