/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................myCar.BatteryState
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_MYCAR_BATTERYSTATE_AUTOMATIC_H_
#define _ASD_MYCAR_BATTERYSTATE_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#if (!defined(ESDL_HEADER_VERSION) || (ESDL_HEADER_VERSION < 5))
# error NOT COMPLIANT (< compliance level 5) VERSION OF esdl.h FOUND; To fix that, delete the old headers (esdl_<...>.h) in include folder and restart build again to get the new version of those files.
#endif
#include "chartab.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'myCar_BatteryState_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct myCar_BatteryState_Automatic_RAM_SUBSTRUCT {
   float32 battery;
   float32 powerInput;
   float32 powerOverride;
   float32 recupMult;
   boolean noRecupPossible;
   uint8 sm;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'myCar_BatteryState_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR CLASS 'myCar_BatteryState_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct myCar_BatteryState_Automatic {
   struct myCar_BatteryState_Automatic_RAM_SUBSTRUCT * myCar_BatteryState_Automatic_RAM;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR CLASS 'myCar_BatteryState_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ...............myCar_BatteryState_Automatic */
#define _myCar_BatteryState_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by class myCar_BatteryState_Automatic
 ******************************************************************************/
extern void myCar_BatteryState_Automatic_batteryStateStatemachineTrigger ( const struct myCar_BatteryState_Automatic * self);
uint8 myCar_BatteryState_Automatic_esdl_getState ( const struct myCar_BatteryState_Automatic * self);



#endif /* _ASD_MYCAR_BATTERYSTATE_AUTOMATIC_H_ */
