/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................myCar.SplitSignal
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "myCar_SplitSignal_Automatic.h"
/******************************************************************************
 * BEGIN: source code of a multiple instance class
 ******************************************************************************/



#define minus_VAL (self->myCar_SplitSignal_Automatic_RAM->minus)
#define plus_VAL (self->myCar_SplitSignal_Automatic_RAM->plus)


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'myCar_SplitSignal_Automatic_calc'
 * ----------------------------------------------------------------------------
 * model name:...................................'calc'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void myCar_SplitSignal_Automatic_calc (
               const struct myCar_SplitSignal_Automatic * self,
   /* IN    */ const float32                              arg
   )
{
   if (SystemLib_Comparators_GreaterZero_Impl_value((float64)arg))
   {
      plus_VAL = arg;
      minus_VAL = 0.0F;
   }
   else
   {
      minus_VAL = -arg;
      plus_VAL = 0.0F;
   } /* end if */
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'myCar_SplitSignal_Automatic_calc'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



