/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................myCar.TargetVelocity
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    Private access macros
 ******************************************************************************/
#ifndef ESDL_MYCAR_TARGETVELOCITY_AUTOMATIC_PRIVATE
#define ESDL_MYCAR_TARGETVELOCITY_AUTOMATIC_PRIVATE

/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define v_VAL self->myCar_TargetVelocity_Automatic_RAM->v
#define dv_VAL self->myCar_TargetVelocity_Automatic_CAL_MEM->dv
#define mn_VAL self->myCar_TargetVelocity_Automatic_CAL_MEM->mn
#define mx_VAL self->myCar_TargetVelocity_Automatic_CAL_MEM->mx
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* ESDL_MYCAR_TARGETVELOCITY_AUTOMATIC_PRIVATE */

