/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................myCar.myDrive
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "myCar_myDrive_Automatic.h"
#include "ESDL_Linear_Interpolation.h"
/******************************************************************************
 * BEGIN: source code of a multiple instance class
 ******************************************************************************/



#define AirFriction_REF (&(self->myCar_myDrive_Automatic_CAL_MEM->AirFriction))
#define battery_VAL (self->myCar_myDrive_Automatic_RAM->battery)
#define BatteryManager_instance_REF (&(self->BatteryManager_instance))
#define BrakeMomentum_REF (&(self->myCar_myDrive_Automatic_CAL_MEM->BrakeMomentum))
#define cbrt_REF (&(self->myCar_myDrive_Automatic_CAL_MEM->cbrt))
#define dist_VAL (self->myCar_myDrive_Automatic_RAM->dist)
#define DistanceManager_instance_REF (&(self->DistanceManager_instance))
#define ds_VAL (self->myCar_myDrive_Automatic_RAM->ds)
#define EngineMomentum_REF (&(self->myCar_myDrive_Automatic_CAL_MEM->EngineMomentum))
#define momentum_VAL (self->myCar_myDrive_Automatic_RAM->momentum)
#define noRecupPossible_VAL (self->myCar_myDrive_Automatic_RAM->noRecupPossible)
#define power_VAL (self->myCar_myDrive_Automatic_RAM->power)
#define recup_momentum_VAL (self->myCar_myDrive_Automatic_RAM->recup_momentum)
#define recupMult_VAL (self->myCar_myDrive_Automatic_RAM->recupMult)
#define totalDist_VAL (self->myCar_myDrive_Automatic_RAM->totalDist)
#define v_VAL (self->myCar_myDrive_Automatic_RAM->v)


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'myCar_myDrive_Automatic_move'
 * ----------------------------------------------------------------------------
 * model name:...................................'move'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void myCar_myDrive_Automatic_move (
               const struct myCar_myDrive_Automatic * self,
   /* IN    */ const float32                          powerCtrl,
   /* IN    */ const float32                          brakeCtrl,
   /* IN    */ const float32                          mydt,
   /* IN    */ const float32                          myg,
   /* IN    */ const float32                          recupCtrl
   )
{
   v_VAL
      = ((ESDL_Linear_CharTable1_getAt_r32r32((BrakeMomentum_REF)->xSize, (BrakeMomentum_REF)->xDist, (BrakeMomentum_REF)->values, brakeCtrl) + momentum_VAL + ESDL_Linear_CharTable1_getAt_r32r32((AirFriction_REF)->xSize, (AirFriction_REF)->xDist, (AirFriction_REF)->values, v_VAL) + recup_momentum_VAL + myCar_DistanceManager_Automatic_move(DistanceManager_instance_REF, mydt, v_VAL, myg)) * mydt * 3.6F) + v_VAL;
   if (v_VAL < 0.0F)
   {
      v_VAL = 0.0F;
   } /* end if */
   momentum_VAL
      = ESDL_Linear_CharTable2_getAt_r32r32r32((EngineMomentum_REF)->xSize, (EngineMomentum_REF)->xDist, (EngineMomentum_REF)->ySize, (EngineMomentum_REF)->yDist, (EngineMomentum_REF)->values, power_VAL, v_VAL);
   recup_momentum_VAL
      = ESDL_Linear_CharTable1_getAt_r32r32((cbrt_REF)->xSize, (cbrt_REF)->xDist, (cbrt_REF)->values, v_VAL) * recupCtrl * recupMult_VAL * 0.01F;
   dist_VAL
      = self->DistanceManager_instance.myCar_DistanceManager_Automatic_RAM->dist;
   totalDist_VAL
      = self->DistanceManager_instance.myCar_DistanceManager_Automatic_RAM->totalDist;
   ds_VAL
      = self->DistanceManager_instance.myCar_DistanceManager_Automatic_RAM->ds;
   power_VAL
      = myCar_BatteryManager_Automatic_calc_power(BatteryManager_instance_REF, powerCtrl, momentum_VAL, recup_momentum_VAL, ds_VAL);
   recupMult_VAL
      = self->BatteryManager_instance.myCar_BatteryManager_Automatic_RAM->recupMult;
   noRecupPossible_VAL
      = self->BatteryManager_instance.myCar_BatteryManager_Automatic_RAM->noRecupPossible;
   battery_VAL
      = self->BatteryManager_instance.myCar_BatteryManager_Automatic_RAM->battery;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'myCar_myDrive_Automatic_move'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



