/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................myCar.Driver
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    Private access macros
 ******************************************************************************/
#ifndef ESDL_MYCAR_DRIVER_AUTOMATIC_PRIVATE
#define ESDL_MYCAR_DRIVER_AUTOMATIC_PRIVATE

/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define power_VAL myCar_Driver_CAL_MEM.power
#define brake_VAL myCar_Driver_CAL_MEM.brake
#define on_VAL myCar_Driver_CAL_MEM.on
#define inc_VAL myCar_Driver_CAL_MEM.inc
#define dec_VAL myCar_Driver_CAL_MEM.dec
#define manual_recup_VAL myCar_Driver_CAL_MEM.manual_recup
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* ESDL_MYCAR_DRIVER_AUTOMATIC_PRIVATE */

