/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................myCar.CCF
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_MYCAR_CCF_AUTOMATIC_H_
#define _ASD_MYCAR_CCF_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#if (!defined(ESDL_HEADER_VERSION) || (ESDL_HEADER_VERSION < 5))
# error NOT COMPLIANT (< compliance level 5) VERSION OF esdl.h FOUND; To fix that, delete the old headers (esdl_<...>.h) in include folder and restart build again to get the new version of those files.
#endif
#include "chartab.h"
#include "myCar_CCFState_Automatic.h"
#include "myCar_SplitSignal_Automatic.h"
#include "myCar_TargetVelocity_Automatic.h"
#include "SystemLib_Comparators_GreaterZero_Impl.h"
#include "SystemLib_Miscellaneous_EdgeRising_Impl.h"
#include "SystemLib_Nonlinears_Limiter_Impl.h"
#include "SystemLib_Transferfunction_Control_PI_Impl.h"
#include "SystemLib_Transferfunction_Control_PID_Impl.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'myCar_CCF_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * ---------------------------------------------------------------------------*/
struct myCar_CCF_Automatic_CAL_MEM_SUBSTRUCT {
   float32 K;
   float32 TN;
   float32 TV;
   float32 brake;
   float32 c;
   float32 mn;
   float32 mx;
   float32 power;
   float32 vs;
   boolean useSilly;
   boolean withRecup;
   struct myCar_TargetVelocity_Automatic_CAL_MEM_SUBSTRUCT TVI;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'myCar_CCF_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'myCar_CCF_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct myCar_CCF_Automatic_RAM_SUBSTRUCT {
   float32 br;
   float32 ctl;
   float32 vsoll;
   struct myCar_CCFState_Automatic_RAM_SUBSTRUCT CCFS;
   struct SystemLib_Miscellaneous_EdgeRising_Impl_RAM_SUBSTRUCT DecRising;
   struct SystemLib_Miscellaneous_EdgeRising_Impl_RAM_SUBSTRUCT IncRising;
   struct SystemLib_Miscellaneous_EdgeRising_Impl_RAM_SUBSTRUCT OnRising;
   struct SystemLib_Transferfunction_Control_PID_Impl_RAM_SUBSTRUCT PID_instance;
   struct SystemLib_Transferfunction_Control_PI_Impl_RAM_SUBSTRUCT PI_instance;
   struct myCar_SplitSignal_Automatic_RAM_SUBSTRUCT SplitSignal_instance;
   struct myCar_TargetVelocity_Automatic_RAM_SUBSTRUCT TVI;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'myCar_CCF_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR MODULE 'myCar_CCF_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct myCar_CCF_Automatic {
   struct myCar_CCFState_Automatic CCFS;
   struct SystemLib_Miscellaneous_EdgeRising_Impl DecRising;
   struct SystemLib_Miscellaneous_EdgeRising_Impl IncRising;
   struct SystemLib_Miscellaneous_EdgeRising_Impl OnRising;
   struct SystemLib_Transferfunction_Control_PID_Impl PID_instance;
   struct SystemLib_Transferfunction_Control_PI_Impl PI_instance;
   struct myCar_SplitSignal_Automatic SplitSignal_instance;
   struct myCar_TargetVelocity_Automatic TVI;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR MODULE 'myCar_CCF_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ........................myCar_CCF_Automatic */
#define _myCar_CCF_Automatic_TYPE_DEF_




/* forward declaration of substruct variable 'myCar_CCF_CAL_MEM' */
/* containing 'CAL_MEM' memory class tree */
extern struct myCar_CCF_Automatic_CAL_MEM_SUBSTRUCT myCar_CCF_CAL_MEM;

/* forward declaration of substruct variable 'myCar_CCF_RAM' */
/* containing 'RAM' memory class tree */
extern struct myCar_CCF_Automatic_RAM_SUBSTRUCT myCar_CCF_RAM;

/* forward declaration of component variable 'myCar_CCF' */
/* containing 'ROM' memory class tree */
extern const struct myCar_CCF_Automatic myCar_CCF;

/******************************************************************************
 * BEGIN: declaration of global C functions defined by module myCar_CCF_Automatic
 ******************************************************************************/
extern void myCar_CCF_Automatic_calc (void);



#endif /* _ASD_MYCAR_CCF_AUTOMATIC_H_ */
