/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................resources.CarMessages
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    Private access macros
 ******************************************************************************/
#ifndef ESDL_RESOURCES_CARMESSAGES_AUTOMATIC_PRIVATE
#define ESDL_RESOURCES_CARMESSAGES_AUTOMATIC_PRIVATE

/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define resources_CarMessages_v_VAL resources_CarMessages_v
#define resources_CarMessages_power_VAL resources_CarMessages_power
#define resources_CarMessages_brake_VAL resources_CarMessages_brake
#define resources_CarMessages_recuperation_VAL resources_CarMessages_recuperation
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* ESDL_RESOURCES_CARMESSAGES_AUTOMATIC_PRIVATE */

