/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................resources.DriverMessages
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    Private access macros
 ******************************************************************************/
#ifndef ESDL_RESOURCES_DRIVERMESSAGES_AUTOMATIC_PRIVATE
#define ESDL_RESOURCES_DRIVERMESSAGES_AUTOMATIC_PRIVATE

/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define resources_DriverMessages_brake_VAL resources_DriverMessages_brake
#define resources_DriverMessages_power_VAL resources_DriverMessages_power
#define resources_DriverMessages_on_VAL resources_DriverMessages_on
#define resources_DriverMessages_display_VAL resources_DriverMessages_display
#define resources_DriverMessages_increment_VAL resources_DriverMessages_increment
#define resources_DriverMessages_decrement_VAL resources_DriverMessages_decrement
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* ESDL_RESOURCES_DRIVERMESSAGES_AUTOMATIC_PRIVATE */

