/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................resources.DriverMessages
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "resources_DriverMessages_Automatic.h"


/******************************************************************************
 * DEFINITION OF COMPONENT VARIABLE OMITTED
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'resources_DriverMessages'
 * reason:.......................................no local elements
 * ---------------------------------------------------------------------------*/






/******************************************************************************
 * BEGIN: DEFINITION OF MESSAGES
 * ----------------------------------------------------------------------------
 * Total size is [bytes]:........................12
 * ---------------------------------------------------------------------------*/
/* messages of memory class:............................................'RAM' */
/* messages of size [bytes]:................................................4 */
/* modelled as 'resources_DriverMessages_brake' */
float32 resources_DriverMessages_brake = 0.0F;
/* modelled as 'resources_DriverMessages_power' */
float32 resources_DriverMessages_power = 0.0F;
/* messages of size [bytes]:................................................1 */
/* modelled as 'resources_DriverMessages_decrement' */
boolean resources_DriverMessages_decrement = false;
/* modelled as 'resources_DriverMessages_display' */
boolean resources_DriverMessages_display = false;
/* modelled as 'resources_DriverMessages_increment' */
boolean resources_DriverMessages_increment = false;
/* modelled as 'resources_DriverMessages_on' */
boolean resources_DriverMessages_on = false;
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MESSAGES
 ******************************************************************************/



/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/

/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



