/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................resources.DriverMessages
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_RESOURCES_DRIVERMESSAGES_AUTOMATIC_H_
#define _ASD_RESOURCES_DRIVERMESSAGES_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#if (!defined(ESDL_HEADER_VERSION) || (ESDL_HEADER_VERSION < 5))
# error NOT COMPLIANT (< compliance level 5) VERSION OF esdl.h FOUND; To fix that, delete the old headers (esdl_<...>.h) in include folder and restart build again to get the new version of those files.
#endif
#include "chartab.h"


/* component structure for module RESOURCES_DRIVERMESSAGES_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: .........resources_DriverMessages_Automatic */
#define _resources_DriverMessages_Automatic_TYPE_DEF_



/******************************************************************************
 * BEGIN: declaration of global C variables exported by module resources_DriverMessages_Automatic
 ******************************************************************************/


/* declaration of messages */
extern float32 resources_DriverMessages_brake;
extern boolean resources_DriverMessages_decrement;
extern boolean resources_DriverMessages_display;
extern boolean resources_DriverMessages_increment;
extern boolean resources_DriverMessages_on;
extern float32 resources_DriverMessages_power;


#endif /* _ASD_RESOURCES_DRIVERMESSAGES_AUTOMATIC_H_ */
