/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................SystemLib.Miscellaneous.DeltaTimeService
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    Private access macros
 ******************************************************************************/
#ifndef ESDL_SYSTEMLIB_MISCELLANEOUS_DELTATIMESERVICE_AUTOMATIC_PRIVATE
#define ESDL_SYSTEMLIB_MISCELLANEOUS_DELTATIMESERVICE_AUTOMATIC_PRIVATE

/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define SystemLib_Miscellaneous_DeltaTimeService_deltaT_VAL SystemLib_Miscellaneous_DeltaTimeService_deltaT
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* ESDL_SYSTEMLIB_MISCELLANEOUS_DELTATIMESERVICE_AUTOMATIC_PRIVATE */

