/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................SystemLib.Nonlinears.Limiter
 * REPRESENTATION:..............Impl
 * DESCRIPTION:
 *    Private access macros
 ******************************************************************************/
#ifndef ESDL_SYSTEMLIB_NONLINEARS_LIMITER_IMPL_PRIVATE
#define ESDL_SYSTEMLIB_NONLINEARS_LIMITER_IMPL_PRIVATE

/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* ESDL_SYSTEMLIB_NONLINEARS_LIMITER_IMPL_PRIVATE */

