/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................SystemLib.Transferfunction.Control.PID
 * REPRESENTATION:..............Impl
 * DESCRIPTION:
 *    PID is a time discrete proportional integrator with differential part with time constants TV and TN and gain constant K.
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "SystemLib_Transferfunction_Control_PID_Impl.h"
#include "SystemLib_Miscellaneous_DeltaTimeService_Automatic.h"
/******************************************************************************
 * BEGIN: source code of a multiple instance class
 ******************************************************************************/



#define inOLD_VAL (self->SystemLib_Transferfunction_Control_PID_Impl_RAM->inOLD)
#define memory1_VAL (self->SystemLib_Transferfunction_Control_PID_Impl_RAM->memory1)
#define memory2_VAL (self->SystemLib_Transferfunction_Control_PID_Impl_RAM->memory2)
#define SystemLib_Miscellaneous_DeltaTimeService_deltaT_VAL (SystemLib_Miscellaneous_DeltaTimeService_deltaT)


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'SystemLib_Transferfunction_Control_PID_Impl_compute'
 * ----------------------------------------------------------------------------
 * model name:...................................'compute'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void SystemLib_Transferfunction_Control_PID_Impl_compute (
               const struct SystemLib_Transferfunction_Control_PID_Impl * self,
   /* IN    */ const float64                                              val,
   /* IN    */ const float64                                              K,
   /* IN    */ const float64                                              TV,
   /* IN    */ const float64                                              TN
   )
{
   /* temp. variables */
   float64 _t1real64;

   memory1_VAL
      = (SystemLib_Miscellaneous_DeltaTimeService_deltaT_VAL * val * (((TN == 0.0) ? K : (K / TN)))) + memory1_VAL;
   _t1real64 = K * TV;
   memory2_VAL
      = ((((SystemLib_Miscellaneous_DeltaTimeService_deltaT_VAL == 0.0) ? _t1real64 : (_t1real64 / SystemLib_Miscellaneous_DeltaTimeService_deltaT_VAL))) * (val - inOLD_VAL)) + memory1_VAL + (val * K);
   inOLD_VAL = val;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'SystemLib_Transferfunction_Control_PID_Impl_compute'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'SystemLib_Transferfunction_Control_PID_Impl_reset'
 * ----------------------------------------------------------------------------
 * model name:...................................'reset'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void SystemLib_Transferfunction_Control_PID_Impl_reset (
               const struct SystemLib_Transferfunction_Control_PID_Impl * self,
   /* IN    */ const float64                                              initValue
   )
{
   memory1_VAL = initValue;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'SystemLib_Transferfunction_Control_PID_Impl_reset'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'SystemLib_Transferfunction_Control_PID_Impl_value'
 * ----------------------------------------------------------------------------
 * model name:...................................'value'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float64 SystemLib_Transferfunction_Control_PID_Impl_value ( const struct SystemLib_Transferfunction_Control_PID_Impl * self)
{
   return memory2_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'SystemLib_Transferfunction_Control_PID_Impl_value'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



