/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................SystemLib.Transferfunction.Control.PI
 * REPRESENTATION:..............Impl
 * DESCRIPTION:
 *    PI is a time discrete proportional integrator with time constant T and gain constant K.
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "SystemLib_Transferfunction_Control_PI_Impl.h"
#include "SystemLib_Miscellaneous_DeltaTimeService_Automatic.h"
/******************************************************************************
 * BEGIN: source code of a multiple instance class
 ******************************************************************************/



#define memory1_VAL (self->SystemLib_Transferfunction_Control_PI_Impl_RAM->memory1)
#define memory2_VAL (self->SystemLib_Transferfunction_Control_PI_Impl_RAM->memory2)
#define SystemLib_Miscellaneous_DeltaTimeService_deltaT_VAL (SystemLib_Miscellaneous_DeltaTimeService_deltaT)


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'SystemLib_Transferfunction_Control_PI_Impl_compute'
 * ----------------------------------------------------------------------------
 * model name:...................................'compute'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void SystemLib_Transferfunction_Control_PI_Impl_compute (
               const struct SystemLib_Transferfunction_Control_PI_Impl * self,
   /* IN    */ const float64                                             val,
   /* IN    */ const float64                                             K,
   /* IN    */ const float64                                             T
   )
{
   memory1_VAL
      = ((((T == 0.0) ? K : (K / T))) * val * SystemLib_Miscellaneous_DeltaTimeService_deltaT_VAL) + memory1_VAL;
   memory2_VAL = memory1_VAL + (val * K);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'SystemLib_Transferfunction_Control_PI_Impl_compute'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'SystemLib_Transferfunction_Control_PI_Impl_reset'
 * ----------------------------------------------------------------------------
 * model name:...................................'reset'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void SystemLib_Transferfunction_Control_PI_Impl_reset (
               const struct SystemLib_Transferfunction_Control_PI_Impl * self,
   /* IN    */ const float64                                             initValue
   )
{
   memory1_VAL = initValue;
   memory2_VAL = memory1_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'SystemLib_Transferfunction_Control_PI_Impl_reset'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'SystemLib_Transferfunction_Control_PI_Impl_value'
 * ----------------------------------------------------------------------------
 * model name:...................................'value'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float64 SystemLib_Transferfunction_Control_PI_Impl_value ( const struct SystemLib_Transferfunction_Control_PI_Impl * self)
{
   return memory2_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'SystemLib_Transferfunction_Control_PI_Impl_value'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



