/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................SystemLib.Transferfunction.Control.PI
 * REPRESENTATION:..............Impl
 * DESCRIPTION:
 *    Private access macros
 ******************************************************************************/
#ifndef ESDL_SYSTEMLIB_TRANSFERFUNCTION_CONTROL_PI_IMPL_PRIVATE
#define ESDL_SYSTEMLIB_TRANSFERFUNCTION_CONTROL_PI_IMPL_PRIVATE

/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define memory1_VAL self->SystemLib_Transferfunction_Control_PI_Impl_RAM->memory1
#define memory2_VAL self->SystemLib_Transferfunction_Control_PI_Impl_RAM->memory2
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* ESDL_SYSTEMLIB_TRANSFERFUNCTION_CONTROL_PI_IMPL_PRIVATE */

