/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................SystemLib.Transferfunction.Control.PI
 * REPRESENTATION:..............Impl
 * DESCRIPTION:
 *    PI is a time discrete proportional integrator with time constant T and gain constant K.
 ******************************************************************************/
#ifndef _ASD_SYSTEMLIB_TRANSFERFUNCTION_CONTROL_PI_IMPL_H_
#define _ASD_SYSTEMLIB_TRANSFERFUNCTION_CONTROL_PI_IMPL_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#if (!defined(ESDL_HEADER_VERSION) || (ESDL_HEADER_VERSION < 5))
# error NOT COMPLIANT (< compliance level 5) VERSION OF esdl.h FOUND; To fix that, delete the old headers (esdl_<...>.h) in include folder and restart build again to get the new version of those files.
#endif
#include "chartab.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'SystemLib_Transferfunction_Control_PI_Impl'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct SystemLib_Transferfunction_Control_PI_Impl_RAM_SUBSTRUCT {
   float64 memory1;
   float64 memory2;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'SystemLib_Transferfunction_Control_PI_Impl'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR CLASS 'SystemLib_Transferfunction_Control_PI_Impl'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct SystemLib_Transferfunction_Control_PI_Impl {
   struct SystemLib_Transferfunction_Control_PI_Impl_RAM_SUBSTRUCT * SystemLib_Transferfunction_Control_PI_Impl_RAM;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR CLASS 'SystemLib_Transferfunction_Control_PI_Impl'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: .SystemLib_Transferfunction_Control_PI_Impl */
#define _SystemLib_Transferfunction_Control_PI_Impl_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by class SystemLib_Transferfunction_Control_PI_Impl
 ******************************************************************************/
extern void SystemLib_Transferfunction_Control_PI_Impl_compute (
               const struct SystemLib_Transferfunction_Control_PI_Impl * self,
   /* IN    */ const float64                                             val,
   /* IN    */ const float64                                             K,
   /* IN    */ const float64                                             T
   );
extern void SystemLib_Transferfunction_Control_PI_Impl_reset (
               const struct SystemLib_Transferfunction_Control_PI_Impl * self,
   /* IN    */ const float64                                             initValue
   );
extern float64 SystemLib_Transferfunction_Control_PI_Impl_value ( const struct SystemLib_Transferfunction_Control_PI_Impl * self);



#endif /* _ASD_SYSTEMLIB_TRANSFERFUNCTION_CONTROL_PI_IMPL_H_ */
