/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................SystemLib.Comparators.GreaterZero
 * REPRESENTATION:..............Impl
 * DESCRIPTION:
 *    GreaterZero returns TRUE if the value val is greater than zero.
 ******************************************************************************/
#ifndef _ASD_SYSTEMLIB_COMPARATORS_GREATERZERO_IMPL_H_
#define _ASD_SYSTEMLIB_COMPARATORS_GREATERZERO_IMPL_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#if (!defined(ESDL_HEADER_VERSION) || (ESDL_HEADER_VERSION < 5))
# error NOT COMPLIANT (< compliance level 5) VERSION OF esdl.h FOUND; To fix that, delete the old headers (esdl_<...>.h) in include folder and restart build again to get the new version of those files.
#endif
#include "chartab.h"


/* component structure for class SYSTEMLIB_COMPARATORS_GREATERZERO_IMPL intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: .....SystemLib_Comparators_GreaterZero_Impl */
#define _SystemLib_Comparators_GreaterZero_Impl_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by class SystemLib_Comparators_GreaterZero_Impl
 ******************************************************************************/
extern sint16 SystemLib_Comparators_GreaterZero_Impl_value (/* IN    */ const float64 val);



#endif /* _ASD_SYSTEMLIB_COMPARATORS_GREATERZERO_IMPL_H_ */
